# Colors (monochrome)

# Default colors
[colors.primary]
background = '#333333'
foreground = '#aaaaaa'

# Normal colors
[colors.normal]
black = '#333333'
red = '#6c6c6c'
green = '#969696'
yellow = '#a4a4a4'
blue = '#4d4d4d'
magenta = '#696969'
cyan = '#a2a2a2'
white = '#aaaaaa'

# Bright colors
[colors.bright]
black = '#474747'
red = '#7c7c7c'
green = '#a6a6a6'
yellow = '#b4b4b4'
blue = '#6d6d6d'
magenta = '#797979'
cyan = '#b2b2b2'
white = '#bbbbbb'

